spring.application.name=spring-ai-playground
spring.devtools.restart.enabled=true

spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.model=mistral
spring.ai.ollama.chat.model=qwen2.5:7b-instruct
spring.ai.ollama.embedding.model=nomic-embed-text


spring.datasource.url=jdbc:h2:mem:supportdb;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.driver-class-name=org.h2.Driver

logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.web.client=DEBUG

#MCP server config
spring.ai.mcp.server.name=${spring.application.name}
spring.ai.mcp.server.version=1.0.0
#spring.ai.mcp.server.protocol=STREAMABLE

# Add these to force SSE/HTTP transport:
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.sse-endpoint=/sse
spring.ai.mcp.server.sse-message-endpoint=/mcp/message
